set :application,         "recessmobile"
set :repository,          "git@holmes.unfuddle.com:holmes/rm-typus-app.git"
set :domain,              "recessmobile.com"
set :rails_env,           "production"
set :user,                "recess"
set :runner,              "recess"
set :deploy_to,           "/home/#{user}/#{application}"

default_run_options[:pty] = true
ssh_options[:paranoid]    = false

set :use_sudo,            false

set :scm,                 :git
set :branch,              "master"

# don't use export as it will clear out the .git directories prematurely.
# we'll remove them ourselves later when we're done with using git
set :deploy_via,          :checkout

# set these values with proc-value to delay evaluation and properly handle overrides (e.g. deploy_to)
set(:current_path)        { "#{deploy_to}/current" }  # A hack since cap 2.3.0 uses /u/apps sometimes

role :app, domain
role :web, domain
role :db,  domain, :primary => true

# Create uploads directory and link, remove rep clone
task :after_update_code, :roles => :app do
  run "cp #{shared_path}/config/database.yml #{release_path}/config/database.yml"
  run "rm -Rf #{release_path}/.git" if fetch(:deploy_to) != :export
  run "mkdir -p #{shared_path}/bundle && ln -s #{shared_path}/bundle #{release_path}/vendor/bundle"
  run "cd #{latest_release}; /opt/ruby/bin/bundle install --deployment --without development test"
end

# Passenger tasks
namespace :deploy do
  desc "Restarting mod_rails with restart.txt"
  task :restart, :roles => :app, :except => { :no_release => true } do
    run "touch #{current_path}/tmp/restart.txt"
  end

  [:start, :stop].each do |t|
    desc "#{t} task is a no-op with mod_rails"
    task t, :roles => :app do ; end
  end
end

namespace :sass do
  desc 'Updates the stylesheets generated by Sass'
  task :update, :roles => :app do
    invoke_command "cd #{latest_release}; RAILS_ENV=#{rails_env} /opt/ruby/bin/bundle rake sass:update"
  end

  # Generate all the stylesheets manually (from their Sass templates) before each restart.
  before 'deploy:restart', 'sass:update'
end

namespace :db do
  task :seed do
    run "cd #{latest_release}; RAILS_ENV=#{rails_env} /opt/ruby/bin/bundle rake db:seed"
  end
end

after "deploy:restart", "deploy:cleanup"

        # inserted by Hoptoad:
        # require 'config/boot'
        require 'hoptoad_notifier/capistrano'
